version: "3.5"
services:
  django_docker_demo:
    build: .
    networks:
      demo-net:
    volumes:
      - ./static:/code/static
      - demo_media:/code/media
      - ./uwsgi:/code/uwsgi
  nginx:
    build: ./nginx
    ports:
      - "8083:80"
    networks:
      demo-net:
    volumes:
      - ./nginx/ssl:/usr/share/nginx/ssl  # 挂载ssl证书目录
      - ./nginx/nginx.log:/var/log/nginx  # 挂载日志
      - ./static:/usr/share/nginx/html/static
      - demo_media:/usr/share/nginx/html/media

networks:
  demo-net:

volumes:
  demo_media: